version: "3.8"

services:
  app:
    build: .
    container_name: cine-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - PORT=3000
      - HOST=db
      - USER=root
      - PASSWORD=rootpass
      - DB=CINE
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: cine-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: CINE
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/config/mysql/database:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  db_data:
