CREATE DATABASE IF NOT EXISTS CINE;
USE CINE;

CREATE TABLE IF NOT EXISTS PELICULAS(
	ID				INT			AUTO_INCREMENT PRIMARY KEY,
    TITULO			VARCHAR(50) NOT NULL,
    DURACION_MIN	SMALLINT NOT NULL,
    CLASFICIACION 	ENUM('APT','+14','+18') NOT NULL,
    LANZAMIENTO		CHAR(4)	NOT NULL,
    created_at 		DATETIME,
    updated_at 		DATETIME,
    deleted_at 		DATETIME
)ENGINE=INNODB;
