INSERT INTO PELICULAS (TITULO, DURACION_MIN, CLASIFICACION, LANZAMIENTO, created_at, updated_at)
	VALUES 	('SHERK',110,'APT','2001', NOW(),NOW()),
			('DRAGON BALL Z: LA BATALLA DE LOS DIOSES',90,'APT','2013',NOW(),NOW()),
            ('THUNDERBOLTS*',110,'+18','2025',NOW(),NOW());
		