INSERT INTO PELICULAS (TITULO, DURACION_MIN, CLASFICIACION, LANZAMIENTO)
	VALUES 	('SHERK',110,'APT','2001'),
			    ('DRAGON BALL Z: LA BATALLA DE LOS DIOSES',90,'APT','2013'),
          ('THUNDERBOLTS*',110,'+18','2025');